function [matrix] = rotationMatrix3D(axis, angle)
% Returns the corresponding 3D rotation matrix
    if axis == "X"
        matrix = [ ...
            [1, 0, 0]; ...
            [0, cos(angle), -sin(angle)]; ...
            [0, sin(angle), cos(angle)] ...
        ];
    elseif axis == "Y"
        matrix = [ ...
            [cos(angle), 0, sin(angle)]; ...
            [0, 1, 0]; ...
            [-sin(angle), 0, cos(angle)] ...
        ];
    else
        matrix = [ ...
            [cos(angle), -sin(angle), 0]; ...
            [sin(angle), cos(angle), 0]; ...
            [0, 0, 1] ...
        ];
    end
end

